---
title: Harney County Arts in Education Foundation
timezone: America/Los_Angeles
collections:
  events:
    title: Events
    output: true
    permalink: "/:collection/:path/"
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  programs:
    title: Programs
    output: false
  support:
    title: Support
    output: false
  team-members:
    title: Team Members
    output: false
  uploads:
    title: uploads
    output: true
defaults:
- scope:
    path: ''
    type: news
  values:
    layout: news-detail
    Subtitle: ''
    Author: ''
    Main Image: ''
    Main Image Caption: ''
    Is Featured?: false
- scope:
    path: ''
    type: events
  values:
    layout: event-detail
    Is Featured?: false
    Event Image: 
    Event Image Caption: 
    Event Start Date: 
    Event End Date: 
    Volunteers Needed?: false
    Event Venue: 
    Event Venue Address: 
    Tickets Required?: false
    Ticket Purchasing URL: 
    Instructions for Tickets: 
    Event Info URL: 
- scope:
    path: ''
    type: programs
  values:
    Button:
    - Title: ''
      URL: ''
    Footnote: ''
    Image: ''
    Image First?: false
    List (single):
    - Item: ''
    List (expanded):
    - Item Title: ''
      Item Description: ''
- scope:
    path: ''
    type: support
  values:
    Button:
    - Title: ''
      URL: ''
    Footnote: 
    Image: ''
    Image First?: false
    Table:
    - - ''
      - ''
- scope:
    path: ''
    type: team-members
  values:
    Position Title: ''
    Email Address: ''
    Is Board Member?: false
    Image: ''
email: info@harneyartsfoundation.org
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description. '
baseurl: "/"
url: http://harneyartsfoundation.org
twitter_username: 
share_image_url: 
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- README.md
- sass
- src
