---
title: Harney County Arts in Education Foundation
timezone: America/Los_Angeles
collections:
  events:
    title: Events
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: News
    output: true
  programs:
    title: Programs
    output: false
  support:
    title: Support
    output: false
  team-members:
    title: Team Members
    output: false
  uploads:
    title: uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: news-detail
    Subtitle: ''
    Author: ''
    Image: ''
    Image Caption: ''
    Is Featured?: false
    Feature on Front Page?: false
- scope:
    path: ''
    type: events
  values:
    layout: event-detail
    Is Featured?: false
    Image: ''
    Image Caption: ''
    Event Start Date: 
    Event End Date: 
    Volunteers Needed?: false
    Event Venue: ''
    Event Venue Address: ''
    Tickets Required?: false
    Ticket Purchasing URL: ''
    Instructions for Tickets: ''
    Event Info URL: ''
    Feature on Front Page?: false
- scope:
    path: ''
    type: programs
  values:
    Button:
    - Title: ''
      URL: ''
    Footnote: ''
    Image: ''
    Image Caption: ''
    Image First?: false
    List (single):
    - Item: ''
    List (expanded):
    - Item Title: ''
      Item Description: ''
- scope:
    path: ''
    type: support
  values:
    Button:
    - Title: ''
      URL: ''
    Footnote: ''
    Image: ''
    Image Caption: ''
    Image First?: false
    Table:
    - - ''
      - ''
- scope:
    path: ''
    type: team-members
  values:
    Position Title: ''
    Email Address: ''
    Is Board Member?: false
    Image: ''
email: harneyartsfoundation@gmail.com
description: We are a group of artists, educators, parents, and community members
  that are committed to providing our students and our community with excellent art
  and music education and experiences.
paypal_share_url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2LUZUYG2268NS
baseurl: "/"
url: http://harneyartsfoundation.org
twitter_handle: HCAEF
facebook_page_handle: HarneyArtsFoundation
share_image_url: 
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- README.md
- sass
- src
